/*
 * ============================================================
 * FILE: sst-env.d.ts
 * PURPOSE: Declares generated SST resource bindings when the optional SST environment is used.
 * ============================================================
 */

/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

/// <reference path="../../../sst-env.d.ts" />

import "sst"
export {}
